### ISSUE TITLE
你好,模糊的时候,内存占用厉害

### ISSUE THREAD

**Issue by xiaoyao20084321** [YouXianMing/UIImageBlur#1]
你好,我现在在做这个的时候,获取手指移动位置,然后不停的调用这个demo里的方法,发现内存能达到100 - 300M左右,很卡...而且,发现如果对同一个地方一直模糊,会导致这个地方慢慢的有颜色起来,有没有解决的办法呢,.谢谢

**Comment by xiaoyao20084321** [comment]
调用的是blurImageAtFrame这个方法

**Comment by YouXianMing** [comment]
这个category不适合实时模糊图片,只适合处理静态图.
